Repository openshift/cluster-api-provider-openstack, pull requests merged in 2019-09, with the labels that each got.

#62 Bug 1746369: return an error if the instance has been destroyed
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#63 bug 1746019: Add event recording for machines
  Gopkg.lock
  config/rbac/rbac_role.yaml
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#64 Bug 1747245: return an error if the cluster name label is incorrect
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#66 Bug 1746021: Abort Instance if no valid network
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#67 Bug 1752088: UPSTREAM: <carry>: openshift: Revendor to bring https://github.com/openshift/cluster-api/pull/72
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.toml
  vendor/github.com/openshift/cluster-api/Makefile
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machine.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machineset.yaml
  vendor/github.com/openshift/cluster-api/hack/goimports.sh
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/controller/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/add_node.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/sync.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
  vendor/github.com/openshift/cluster-api/pkg/drain/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/drain/drain.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#69 Bug 1754070: Add boot from volume support
  Gopkg.lock
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/util.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/openshift/kubernetes-drain/LICENSE
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#70 Bug 1754115: Boot from volume
  Gopkg.lock
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/util.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/openshift/kubernetes-drain/LICENSE
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL
