Repository openshift/cluster-api-provider-openstack, pull requests merged in 2019-08, with the labels that each got.

#53 Rename schema group to openshift io
  Makefile
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderstatus.yaml
  config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
  config/rbac/rbac_role.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/doc.go
  pkg/apis/openstackproviderconfig/v1alpha1/register.go
Labels: approved, lgtm, size/S

#56 Refresh cluster-api-openstack-maintainers
  OWNERS_ALIASES
Labels: do-not-merge/invalid-owners-file, size/XS

#55 Bug 1724204: Set additional machine annotations/labels
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#58 limit owners to shiftstack team
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, lgtm, size/M

#59 Bug 1745939: Return error if image creation fails
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#60 Bug 1746015: Return error if instance deletion fails
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#61 Bug 1746015: provide correct API to machine serialization
  pkg/cloud/openstack/machine/instancestatus.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
