Repository openshift/cluster-api-provider-openstack, pull requests merged in 2019-04, with the labels that each got.

#31 Add reviewers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#30 Read clusterName from machine if cluster is nil
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, lgtm, size/S

#29 add machine status
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, lgtm, ok-to-test, size/S

#33 Add CI Dockerfile for e2e test
  Dockerfile.installer.ci
Labels: approved, lgtm, size/S

#34 machine/actuator: Fix Update instance status
  pkg/cloud/openstack/machine/instancestatus.go
Labels: approved, lgtm, size/M

#42 Use local GetMachineIfExists function instead of cluster-api
  pkg/cloud/openstack/machine/instancestatus.go
Labels: approved, lgtm, size/S
