Repository openshift/cluster-api-provider-openstack, pull requests merged in 2019-02, with the labels that each got.

#19 Subnet Support (#228)
  docs/config.md
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, lgtm, size/L

#21 Rebase upstream
  README.md
  docs/config.md
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, lgtm, size/S

#22 Allow for filtering subnets rather than passing an UUID
  Gopkg.lock
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderstatus.yaml
  config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/openstack/clients/machineservice.go
  vendor/github.com/gophercloud/gophercloud/auth_options.go
  vendor/github.com/gophercloud/gophercloud/auth_result.go
  vendor/github.com/gophercloud/gophercloud/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/microversions.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
Labels: approved, lgtm, size/XL

#23 downstream: Remove cluster controller as it's not initialized by the cluster-api
  pkg/controller/add_cluster.go
Labels: approved, lgtm, size/M

#24 Rebase from upstream
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, lgtm, size/M

#25 Pull in sec group filtering
  config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
  docs/config.md
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, lgtm, size/L
