Repository openshift/cluster-api-provider-openstack, pull requests merged in 2020-02, with the labels that each got.

#81 [release-4.3] Bug 1796822: Support deployment on OpenStack with self-signed certificate
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, priority/critical-urgent, size/M

#82 Bug 1751471: Machine update: create before delete
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#84 Add ServerGroupID to OpenstackProviderSpec
  Gopkg.lock
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/requests.go
Labels: approved, lgtm, size/L
