Repository openshift/cluster-api-provider-openstack, pull requests merged in 2020-09, with the labels that each got.

#115 Bug 1872080: Add Dockerfile.rhel to match build configuration in ocp-build-data
  Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#118 Bug 1875036: remove Dockerfile.rhel7
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#117 Bug 1864352: Update leader election for release 4.5
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#121 Bug 1805025: validate that image exists before creating a machine
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#124 Bug 1878880: re-vendor machine-api-operator at e0db6b65
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#123 Bug 1855666: Update klog
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/clients/networkservice.go
  pkg/cloud/openstack/clients/secgroupservice.go
  pkg/cloud/openstack/clients/utils.go
  pkg/cloud/openstack/deployer.go
  pkg/cloud/openstack/machine/actuator.go
  pkg/controller/controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#128 BUG 1875598: Ensure the Virtual Machine provider state is set to Unknown when Failed
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
