Repository openshift/cluster-api-provider-openstack, pull requests merged in 2021-07, with the labels that each got.

#187 hack: Add local-capo.sh
  go.sum
  hack/cvo-unmanage.py
  hack/local-capo.sh
Labels: approved, lgtm

#188 Bug 1943378: Eliminate instanceCreate volume leak
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#189 Bug 1983612: Make InstanceCreate idempotent
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/clients/utils.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#191 Bug 1943378: Fix InstanceCreate volume cleanup
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#182 Remove Fedosin from Owners
  OWNERS_ALIASES
Labels: approved, lgtm

#185 Bug 1964540: Extend trunk configuration to port level in machineset
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
