Repository openshift/cluster-api-provider-openstack, pull requests merged in 2021-03, with the labels that each got.

#166 Tag Ports Created By CAPO Based on Network or Subnet Attached
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/clients/machineservice_test.go
Labels: approved, lgtm

#168 Add availability zone option to root volume
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, lgtm

#169 Adds vnictype to port creation
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/results.go
  vendor/modules.txt
Labels: approved, lgtm

#154 Bug 1933667: Update ose-openstack-machine-controllers builder & base images to be consistent with ART
  Dockerfile
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#171 Bug 1747270: InstanceService.GetInstanceList should not do substring search on name
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#173 Sriov Addons
  Dockerfile
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/results.go
  vendor/modules.txt
Labels: approved, lgtm

#174 Ports NetworkID json typo
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
Labels: approved, lgtm
