Repository openshift/cluster-api-provider-openstack, pull requests merged in 2021-08, with the labels that each got.

#192 Bug 1985015: Eliminate instanceCreate volume leak
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#196 Bug 1986540: Adds Proxy to provider client http transport
  pkg/cloud/openstack/clients/utils.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#195 Bug 1996155: UPSTREAM: 964: getOrCreatePort: add support to configure port Profile
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
