Repository openshift/cluster-api-provider-openstack, pull requests merged in 2021-01, with the labels that each got.

#148 Bug 1913736: do not fetch image id when booting from volume
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#151 Bug 1915926: Update ose-openstack-machine-controllers builder & base …
  Dockerfile
  Dockerfile.rhel
  go.mod
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#157 Bug 1886848: Save status before patching machine annotations
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
