Repository openshift/cluster-api-provider-openstack, pull requests merged in 2022-10, with the labels that each got.

#246 gofmt with Go v1.19
  pkg/bootstrap/token.go
Labels: approved, lgtm

#247 OCPBUGS-2508: Ensure network defs without subnet follow noAllowedAddressPairs
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#249 OCPBUGS-2628: Ensure network defs without subnet follow noAllowedAddressPairs
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug
