Repository openshift/cluster-api-provider-openstack, pull requests merged in 2022-04, with the labels that each got.

#229 Downstream owners
  OWNERS
  OWNERS_ALIASES
Labels: lgtm

#227 Merge upstream kubernetes-sigs/cluster-api-provider-openstack
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/openstackmachine_types.go
  api/v1alpha4/openstackmachine_types.go
  api/v1beta1/openstackmachine_types.go
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  go.mod
  go.sum
  hack/ci/create_devstack.sh
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/service.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/service.go
  pkg/record/recorder.go
  pkg/scope/scope.go
Labels: approved, lgtm

#230 Update from kubernetes-sigs/cluster-api-provider-openstack
  Makefile
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/openstackcluster_conversion.go
  api/v1alpha4/openstackcluster_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  controllers/suite_test.go
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/securitygroups.go
  scripts/go_install.sh
  templates/cluster-template-external-cloud-provider.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-external-cloud-provider.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-multi-az.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-multi-network.yaml
  test/e2e/data/infrastructure-openstack/cluster-template.yaml
Labels: approved, lgtm

#232 Bug 2073398: Fix InstanceCreate port & trunk cleanup
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#236 Merge upstream/release-0.6
  api/v1alpha4/conversion.go
  api/v1alpha4/conversion_test.go
  controllers/openstackcluster_controller.go
  docs/book/src/SUMMARY.md
  docs/book/src/topics/crd-changes/index.md
  docs/book/src/topics/crd-changes/v1alpha4-to-v1alpha5.md
  metadata.yaml
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  test/e2e/shared/openstack.go
Labels: do-not-merge/hold, approved, lgtm
