Repository openshift/cluster-api-provider-openstack, pull requests merged in 2023-12, with the labels that each got.

#284 Add stub e2e target
  openshift/Makefile
Labels: approved, lgtm

#288 OCPBUGS-25639: Add Snyk file to exclude vendor directory on scan
  .snyk
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#289 OCPBUGS-24296: Add Snyk file to exclude vendor directory on scan
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
