Repository openshift/cluster-api-provider-openstack, pull requests merged in 2024-05, with the labels that each got.

#311 OCPBUGS-33170: openshift: Set FallbackToLogsOnError on infra-cluster controller
  openshift/kustomize/infracluster-controller/controller.yaml
  openshift/manifests/0000_30_cluster-api-provider-openstack_04_infrastructure-components.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#312 NO-JIRA: Bump to latest CAPO v0.10
  Makefile
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/types.go
  config/manager/manager.yaml
  main.go
  openshift/manifests/0000_30_cluster-api-provider-openstack_04_infrastructure-components.yaml
  openshift/vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/types.go
  pkg/cloud/services/networking/port.go
  pkg/webhooks/fuzz_test.go
  pkg/webhooks/openstackcluster_webhook.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
Labels: approved, lgtm, jira/valid-reference

#313 Remove dulek from shiftstack-team
  DOWNSTREAM_OWNERS_ALIASES
Labels: approved, lgtm
